// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace IMDB.Test.Feature
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MovieResourceFeature : object, Xunit.IClassFixture<MovieResourceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Movie.feature"
#line hidden
        
        public MovieResourceFeature(MovieResourceFeature.FixtureData fixtureData, IMDB_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Feature", "Movie Resource", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Movie All")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Get Movie All")]
        [Xunit.TraitAttribute("Category", "GetMovieAll")]
        public void GetMovieAll()
        {
            string[] tagsOfScenario = new string[] {
                    "GetMovieAll"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Movie All", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.When("I make GET Request \'/movies\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
 testRunner.Then("response code must be \'200\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
 testRunner.And(@"response data must look like '[{""id"":1,""name"":""Movie 1"",""yearOfRelease"":2020,""plot"":""About the movie"",""language"":""Tamil"",""actors"":[{""id"":1,""name"":""Actor 1"",""bio"":""--"",""dob"":""1990-04-01T00:00:00"",""gender"":""Male"",""image"":""""},{""id"":2,""name"":""Actor "",""bio"":""--"",""dob"":""1997-04-02T00:00:00"",""gender"":""Female"",""image"":""""}],""genre"":[{""id"":1,""name"":""Action""},{""id"":2,""name"":""Horror""}],""producer"":""Producer 1"",""coverImage"":""Image""},{""id"":2,""name"":""Movie 2"",""yearOfRelease"":2021,""plot"":""About the movie"",""language"":""Tamil"",""actors"":[{""id"":1,""name"":""Actor 1"",""bio"":""--"",""dob"":""1990-04-01T00:00:00"",""gender"":""Male"",""image"":""""},{""id"":2,""name"":""Actor "",""bio"":""--"",""dob"":""1997-04-02T00:00:00"",""gender"":""Female"",""image"":""""}],""genre"":[{""id"":1,""name"":""Action""},{""id"":2,""name"":""Horror""}],""producer"":""Producer 2"",""coverImage"":""Image""}]'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Get Movie By Id")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Get Movie By Id")]
        [Xunit.TraitAttribute("Category", "GetMovieById")]
        [Xunit.InlineDataAttribute("/movies/1", "200", @"{""id"":1,""name"":""Movie 1"",""yearOfRelease"":2020,""plot"":""About the movie"",""language"":""Tamil"",""actors"":[{""id"":1,""name"":""Actor 1"",""bio"":""--"",""dob"":""1990-04-01T00:00:00"",""gender"":""Male"",""image"":""""},{""id"":2,""name"":""Actor "",""bio"":""--"",""dob"":""1997-04-02T00:00:00"",""gender"":""Female"",""image"":""""}],""genre"":[{""id"":1,""name"":""Action""},{""id"":2,""name"":""Horror""}],""producer"":""Producer 1"",""coverImage"":""Image""}", new string[0])]
        [Xunit.InlineDataAttribute("/movies/0", "400", "Invalid Id", new string[0])]
        [Xunit.InlineDataAttribute("/movies/4", "404", "Movie 4 is Null (Parameter \'Id\')", new string[0])]
        public void GetMovieById(string endpoint, string statusCode, string response, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "GetMovieById"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Response", response);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Movie By Id", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 11
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 13
 testRunner.When(string.Format("I make GET Request \'{0}\'", endpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 14
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 15
 testRunner.And(string.Format("response data must look like \'{0}\'", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Post Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Post Movie")]
        [Xunit.TraitAttribute("Category", "PostMovie")]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"g" +
            "enre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "201", "{\"id\":0,\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"language\"" +
            ":null,\"actors\":[1,2],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"genre\":[" +
            "1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Name", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":0,\"plot\":\"About the movie\",\"actors\":[1,2],\"genr" +
            "e\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Year Of Release", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"\",\"actors\":[1,2],\"genre\":[1],\"prod" +
            "ucer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Plot", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[],\"genr" +
            "e\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Actors", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"g" +
            "enre\":[],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Genres", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"g" +
            "enre\":[1],\"producer\":\"\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Producer", new string[0])]
        [Xunit.InlineDataAttribute("/movies", "{\"name\":\"Movie 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"g" +
            "enre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"\"}", "400", "Invalid arguments in Movie CoverImage", new string[0])]
        public void PostMovie(string endpoint, string inputData, string statusCode, string response, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PostMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("Input Data", inputData);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Response", response);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 25
 testRunner.When(string.Format("I am making a post request to \'{0}\' with the following Data \'{1}\'", endpoint, inputData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
 testRunner.And(string.Format("response data must look like \'{0}\'", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Put Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Put Movie")]
        [Xunit.TraitAttribute("Category", "PutMovie")]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "200", "", new string[0])]
        [Xunit.InlineDataAttribute("/movies/0", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid Id", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[1,2],\"genre\":[" +
            "1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Name", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":0,\"plot\":\"About the movie\",\"actors\":[1,2" +
            "],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Year Of Release", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"\",\"actors\":[1,2],\"genre\":[1" +
            "],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Plot", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Actors", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Genres", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[1],\"producer\":\"\",\"coverImage\":\"Image\"}", "400", "Invalid arguments in Movie Producer", new string[0])]
        [Xunit.InlineDataAttribute("/movies/1", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"\"}", "400", "Invalid arguments in Movie CoverImage", new string[0])]
        [Xunit.InlineDataAttribute("/movies/4", "{\"name\":\"Movie update 1\",\"yearOfRelease\":2020,\"plot\":\"About the movie\",\"actors\":[" +
            "1,2],\"genre\":[1],\"producer\":\"Producer 1\",\"coverImage\":\"Image\"}", "404", "Movie 4 is Null (Parameter \'Id\')", new string[0])]
        public void PutMovie(string endpoint, string inputData, string statusCode, string response, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PutMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("Input Data", inputData);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Response", response);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Put Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 42
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 43
 testRunner.When(string.Format("I make PUT Request \'{0}\' with the following Data with the following Data \'{1}\'", endpoint, inputData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
 testRunner.And(string.Format("response data must look like \'{0}\'", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Delete Movie")]
        [Xunit.TraitAttribute("FeatureTitle", "Movie Resource")]
        [Xunit.TraitAttribute("Description", "Delete Movie")]
        [Xunit.TraitAttribute("Category", "DeleteMovie")]
        [Xunit.InlineDataAttribute("/movies/1", "200", "", new string[0])]
        [Xunit.InlineDataAttribute("/movies/0", "400", "Invalid Id", new string[0])]
        [Xunit.InlineDataAttribute("/movies/4", "404", "Movie 4 is Null (Parameter \'Id\')", new string[0])]
        public void DeleteMovie(string endpoint, string statusCode, string response, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DeleteMovie"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Endpoint", endpoint);
            argumentsOfScenario.Add("StatusCode", statusCode);
            argumentsOfScenario.Add("Response", response);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete Movie", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 62
 testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 63
 testRunner.When(string.Format("I make Delete Request \'{0}\'", endpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 64
 testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 65
 testRunner.And(string.Format("response data must look like \'{0}\'", response), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                MovieResourceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                MovieResourceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
